#SPDX-License-Identifier: MIT-0
---
# tasks file for role1
- name: Output message
  ansible.builtin.debug:
    msg: "Running role1"
#  tags: download_only

- ansible.builtin.fail:
    msg: "force failure"
  when: force_fail